### PR TITLE
FlatStateDb: commit kernel and user changesets atomically

### LINKED ISSUE #2267: Prevent database corruption on ungraceful shutdown
## Background
Currently, ungraceful shutdowns during DB commit can leave the database in an inconsistent state. 

## Design
To prevent issues, we need to make minor changes to the rollup's startup sequence, the commit-flag enum, and the commit flow.

```rust
enum CommitFlag { 
   Successful { height: u64 },
   ComittingKernelNomt { height: u64 },
   ComittingUserNomt { height: u64 },
   ComittingRocksDB{ height: u64 },
}

```

On startup, check `commit flag`
	1. If status is successful, start from the height +1
	2. If `ComittingKernelNomt`, check whether the commit finished by comparing the NOMT root to the root stored in the live state table. If they match, no rollback is required. Otherwise, roll back kernel NOMT. Start from `height`
	3. If `ComittingUserNomt` in progress, check whether the commit finished by comparing the NOMT root to the root stored in the live state table. If the roots matched, the commit didn't succeed and we're safe.  Start from `height`
		1. If the roots do *not* match, this means NOMT is out of sync with the flat state. To recover we can either
			1. Enable rollback for user NOMT (not ideal)
			2. Skip the consistency check (and update, which would be a no-op anyway) on the next commit
			3. Note that witness generation will be impossible until the next commit. SO, when we enable proving, commit the witness *before* updating the NOMT instance. 

On commit: 
1. Commit ledger and accessory state. These can't be used read block execution - so they should be safe even if they're not fully consistent; they'll get overwritten with the same data when we process the block again (TODO: Verify this is true of accessory state; might be used in sequencer for state root calcs etc.) 
2. Update flag -> `ComittingKernelNomt` { height: u64 },
3. Commit kernel NOMT.
	1. NOMT claims to provide crash fault tolerance through a WAL, so this is atomic
4. Update flag to `ComittingUserNomt`
5. Commit user NOMT
6. Update flag to `CommittingRocksDB`
7. Commit all kernel/user DBs as a unit (remove "other" - it only contains a singleton which can be put in the main DBs;
	1. Commit archival first. If this fails, it'll get overwritten with identical values on the next run
	2. Commit all flat values atomically. 
8. Update flag to Successful

### PR DESCRIPTION
**Pull request by bkolad**
# Description

rockbound update: https://github.com/Sovereign-Labs/rockbound/pull/41

This PR refactors the `FlatStateDb::commit` logic so that `kernel and user` data are now applied atomically to `live_db` and `archival_db`, instead of being updated separately.

The most significant change is in `FlatStateDb::commit`.
Now, the commit flow works as follows:

1. Create `live_db_batch: WriteBatch and archival_db_batch: WriteBatch`
2. Lock the common `kernel/user cache`
3. Apply `kernel` updates to `live_db_batch`
4. Apply `user` updates to `live_db_batch`
(steps 3 and 4 are repeated for `archival_db_batch`)
5. Atomically commit both `archival_db_batch` and `live_db_batch`

This required the following changes in `[rockbound](https://github.com/Sovereign-Labs/rockbound)`:

- Added `VersionedDB::<_, DbCache>::update_versioned_db_batch` method, which accepts a mutable reference to a `WriteBatch`

- The cache for both `kernel` and `user` is now protected by a single lock. As a result, the cache must be created outside of `rockbound::VersionedDB` This was achieved by abstracting the injected component via the `CacheForVersionedDB` trait.

From the above, it becomes clear that we should merge

```
pub(crate) user: Arc<VersionedDB<NomtStateValues<UserNamespace>, DbCache>>,
pub(crate) kernel: Arc<VersionedDB<NomtStateValues<KernelNamespace>, DbCache>>,
```
into a single object (something also briefly discussed with @preston-evans98). In fact, it looks like `FlatStateDb` has  turned into that unified object.

We could remove `live_db and archival_db from VersionedDB` and instead inject them as method parameters—similar to what we now do for cache injection. After additional cleanup and renaming, `FlatStateDb` could be moved to `rockbound`.

I initially attempted this refactor in this PR, but it required extensive changes across `rockbound` and the `sov-db` crate. Given the scope, I decided not to proceed further at this time. If this consolidation is still a priority, we should revisit it once the crash-consistency issue is resolved and all relevant unit tests are passing.

- [ ] I have updated `CHANGELOG.md` with a new entry if my PR makes any breaking changes or fixes a bug. If my PR removes a feature or changes its behavior, I provide help for users on how to migrate to the new behavior.
- [ ] I have carefully reviewed all my `Cargo.toml` changes before opening the PRs. (Are all new dependencies necessary? Is any module dependency leaked into the full-node (hint: it shouldn't)?)

see also https://github.com/Sovereign-Labs/rockbound/pull/41

## Linked Issues
- Fixes # (issue, if applicable)
- Related to # (issue) 

## Testing
Describe how these changes were tested. If you've added new features, have you added unit tests?

## Docs
Describe where this code is documented. If it changes a documented interface, have the docs been updated?

Rendered docs are available at `https://sovlabs-ci-rustdoc-artifacts.us-east-1.amazonaws.com/<BRANCH_NAME>/index.html`

### CODE REVIEW

File: crates/full-node/sov-db/src/flat_db.rs [hunk 1]
```diff
@@ -139,10 +157,133 @@ impl FlatStateDb {
...
+            &mut live_db_batch,
+            &mut archival_db_batch,
+            &state.kernel,
+            version,
+            kernel_cache,
+            &self.live_db,
+            &self.archival_db,
+        )?;
+
+        let serialized_size_kernel = live_db_batch.size_in_bytes();
```
Comment (bkolad) [inline crates/full-node/sov-db/src/flat_db.rs:181]: This is different from https://github.com/Sovereign-Labs/rockbound/blob/main/src/versioned_db.rs#L583. From the code, it looks to me that the previous values (in the link) were wrong. 
We should report live_db_batch.size not live_db_batch.size+archival_db_batch.size

File: crates/full-node/sov-db/src/flat_db.rs [hunk 2]
```diff
@@ -139,10 +157,133 @@ impl FlatStateDb {
...
+            &mut live_db_batch,
+            &state.root_hash_batch,
+            &self.live_db,
+        )?;
+
+        // Write batches.
+        self.archival_db.write_db_batch(archival_db_batch)?;
+        self.kernel.store_committed_archival_version(version);
+        self.user.store_committed_archival_version(version);
+        self.live_db.write_db_batch(live_db_batch)?;
```
Comment (bkolad) [inline crates/full-node/sov-db/src/flat_db.rs:210]: See the PR description. `self.kernel :VersionedDB and self.user: VersionedDB` should likely be merged into one object, but I’d prefer to do that after we address the crash-consistency issue.

rocbound doesn’t know about `Kernel/User` namespaces—it’s a lower-level layer. `sov-db` currently assumes those updates are tracked separately. The changes here are enough to ensure correct cache locking policy and atomic db writes. I suggest we leave the remaining refactor for a follow-up

File: crates/full-node/sov-db/src/flat_db.rs [hunk 3]
```diff
@@ -139,10 +157,133 @@ impl FlatStateDb {
...
+        // 4.Update root hash.
+        DB::update_db_batch_with_schema_data(
+            &mut live_db_batch,
+            &state.root_hash_batch,
+            &self.live_db,
+        )?;
+
+        // Write batches.
+        self.archival_db.write_db_batch(archival_db_batch)?;
+        self.kernel.store_committed_archival_version(version);
```
Comment (preston-evans98) [inline crates/full-node/sov-db/src/flat_db.rs:208]: nit: Let's add a comment that rockbound relies on `store_committed_archival_version` being called before we write the `live_db_batch` to ensure consistency

**Review by preston-evans98 — APPROVED** [review]

File: crates/full-node/sov-db/src/flat_db.rs (hunk 3 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/flat_db.rs:208]: Will update it in the next PR.
