### PR TITLE
Preferred sequencer fail early and cleary on DA-address mismatch

### LINKED ISSUE #2580: Preferred sequencer can detect that its own DA adapter address is not matching preferred sequencer
and exit early with meaningful error

### PR DESCRIPTION
**Pull request by citizen-stig**
# Description

Preferred sequencer checks match between its own `DaService` address and DA address of preferred sequencer in the runtime. Fails early and clearly on mismatch, so operators can fix the error

- [x] I have updated `CHANGELOG.md` with a new entry if my PR makes any breaking changes or fixes a bug. If my PR removes a feature or changes its behavior, I provide help for users on how to migrate to the new behavior.
- [x] I have carefully reviewed all my `Cargo.toml` changes before opening the PRs. (Are all new dependencies necessary? Is any module dependency leaked into the full-node (hint: it shouldn't)?)

## Linked Issues
- Fixes #2580 

## Testing
No

## Docs
No updates

---

<a href="https://app.devin.ai/review/sovereign-labs/sovereign-sdk/pull/2607" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: crates/full-node/sov-sequencer/src/preferred/initialization.rs [hunk 1]
```diff
@@ -64,6 +65,34 @@ where
             .await
             .context("Sequencer must have DaService configured with submit support")?;
 
+        // Early check: verify that this node's DA signer matches the preferred
+        // sequencer registered in the runtime.
+        {
```
Comment (bkolad) [inline crates/full-node/sov-sequencer/src/preferred/initialization.rs]: Let's extract this check to a separate method, as `fn build` is alredy quite long.

**Review by bkolad — APPROVED** [review]
