### PR TITLE
`StorageManager`: Simplify state root validation.

### LINKED ISSUE #2267: Prevent database corruption on ungraceful shutdown
## Background
Currently, ungraceful shutdowns during DB commit can leave the database in an inconsistent state. 

## Design
To prevent issues, we need to make minor changes to the rollup's startup sequence, the commit-flag enum, and the commit flow.

```rust
enum CommitFlag { 
   Successful { height: u64 },
   ComittingKernelNomt { height: u64 },
   ComittingUserNomt { height: u64 },
   ComittingRocksDB{ height: u64 },
}

```

On startup, check `commit flag`
	1. If status is successful, start from the height +1
	2. If `ComittingKernelNomt`, check whether the commit finished by comparing the NOMT root to the root stored in the live state table. If they match, no rollback is required. Otherwise, roll back kernel NOMT. Start from `height`
	3. If `ComittingUserNomt` in progress, check whether the commit finished by comparing the NOMT root to the root stored in the live state table. If the roots matched, the commit didn't succeed and we're safe.  Start from `height`
		1. If the roots do *not* match, this means NOMT is out of sync with the flat state. To recover we can either
			1. Enable rollback for user NOMT (not ideal)
			2. Skip the consistency check (and update, which would be a no-op anyway) on the next commit
			3. Note that witness generation will be impossible until the next commit. SO, when we enable proving, commit the witness *before* updating the NOMT instance. 

On commit: 
1. Commit ledger and accessory state. These can't be used read block execution - so they should be safe even if they're not fully consistent; they'll get overwritten with the same data when we process the block again (TODO: Verify this is true of accessory state; might be used in sequencer for state root calcs etc.) 
2. Update flag -> `ComittingKernelNomt` { height: u64 },
3. Commit kernel NOMT.
	1. NOMT claims to provide crash fault tolerance through a WAL, so this is atomic
4. Update flag to `ComittingUserNomt`
5. Commit user NOMT
6. Update flag to `CommittingRocksDB`
7. Commit all kernel/user DBs as a unit (remove "other" - it only contains a singleton which can be put in the main DBs;
	1. Commit archival first. If this fails, it'll get overwritten with identical values on the next run
	2. Commit all flat values atomically. 
8. Update flag to Successful

### PR DESCRIPTION
**Pull request by bkolad**
# Description

This PR introduces the following changes:

1. Removes `RootHash` from `CommitState`, as this information was redundant—it already exists in the `live_db`, which is committed as the last database.

2. Adds `AllDBsStateRoots`, used for validating state root hashes across different databases. This change replaces the `are_root_hashes_match` method.

- [x] ~I have updated `CHANGELOG.md` with a new entry if my PR makes any breaking changes or fixes a bug. If my PR removes a feature or changes its behavior, I provide help for users on how to migrate to the new behavior.~
- [x] I have carefully reviewed all my `Cargo.toml` changes before opening the PRs. (Are all new dependencies necessary? Is any module dependency leaked into the full-node (hint: it shouldn't)?)

## Linked Issues
- Related to #2267

### CODE REVIEW

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 1]
```diff
@@ -32,6 +32,74 @@ const GIGABYTE: usize = 1024 * 1024 * 1024;
 // without consuming excessive memory.
 pub(crate) const DEFAULT_MAX_PRUNING_BATCH_SIZE: usize = 300_000;
 
+struct AllDBsStateRoots {
+    root_hash_from_live_db: [u8; 64],
+    root_hash_from_ledger_db: [u8; 64],
+    root_hash_nomt: StateRootHashes,
```
Comment (bkolad) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: We will add here hashes also from the other dbs

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 2]
```diff
@@ -216,6 +262,10 @@ where
             CommitStatus::Success => {}
         }
 
+        let state_roots =
+            AllDBsStateRoots::from_dbs(merkelized_state.clone(), ledger_db, flat_state_db)?;
+        state_roots.validate_all();
```
Comment (bkolad) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:198]: After all the rollbacks, validate the state roots.

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 3]
```diff
@@ -32,6 +32,74 @@ const GIGABYTE: usize = 1024 * 1024 * 1024;
 // without consuming excessive memory.
 pub(crate) const DEFAULT_MAX_PRUNING_BATCH_SIZE: usize = 300_000;
 
+struct AllDBsStateRoots {
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: nit: I personally prefer adding new structs at the end of the file.

When I open `groups.rs`, the first thing I expect is to have main struct, which is `DbGroup` in this case

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 4]
```diff
@@ -99,12 +166,8 @@ where
         #[cfg(feature = "test-utils")]
         crate::test_utils::CrashLocation::BeforeSavingLedger.crash_if_env_set();
 
-        // Immediately after genesis, the ledger contains no entries, and the root hash is initialized to [0; 64].
-        let root_hash = LedgerDb::get_head_root_hash(self.ledger.clone())?
-            .unwrap_or_else(|| Self::pre_genesis_root());
-
         self.commit_flag
-            .save_commit_status(&CommitStatus::CommittingLedger(root_hash))?;
+            .save_commit_status(&CommitStatus::CommittingLedger)?;
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:102]: Why don't we save root hash for ledger anymore?

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 5]
```diff
@@ -144,58 +207,41 @@ where
         commit_flag: &CommitFlag,
         merkelized_state: Arc<NomtStateDb<H>>,
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: Non-related, but why it does need arc, and not just & ? Instead of cloning everywhere we can have .as_ref()

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 6]
```diff
@@ -144,58 +207,41 @@ where
...
-                        ?commit_status,
-                        "Detected in-progress commit. Rolling back kernel DB."
-                    );
+                if state_roots.is_user_nomt_root_newer() {
                     merkelized_state.kernel.rollback(1)?;
                     merkelized_state.user.rollback(1)?;
                 } else
                 // Only Kernel commit was successful. We rollback only the kernel.
                 {
-                    tracing::warn!(
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:181]: Why warnings are going away?

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 7]
```diff
@@ -551,3 +548,36 @@ impl PrunerJob {
...
+    else {
+        return Ok(None);
+    };
+
+    let state_root_hash = HistoricalStateReader::get_serialized_root_hash_from_reader(
+        &historical_state_delta_reader,
+        last_version,
+    )?
+    .unwrap_or_else(|| {
+        // If `last_version`` is persent we must always have root hash.
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]:
```suggestion
        // If `last_version` is present we must always have root hash.
```

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 8]
```diff
@@ -551,3 +548,36 @@ impl PrunerJob {
...
+
+// Root hash for empty nomt state.
+fn pre_genesis_root() -> [u8; 64] {
+    let mut pre_genesis_root = [0u8; 64];
+    pre_genesis_root[..32].copy_from_slice(&nomt::trie::TERMINATOR);
+    pre_genesis_root[32..].copy_from_slice(&nomt::trie::TERMINATOR);
+    pre_genesis_root
+}
+
+fn hex(data: &[u8]) -> String {
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: nit: is this function really helpful?

File: crates/full-node/sov-db/src/commit_flag.rs [hunk 9]
```diff
@@ -11,13 +11,12 @@ const FLAG_FILE_NAME: &str = "commit_status.flag";
 #[derive(Debug, PartialEq, Eq, BorshSerialize, BorshDeserialize, Clone, Copy)]
 pub enum CommitStatus {
     /// A commit of **kernel state** is in progress.
-    /// Stores the previous `kernel` root hash before the commit began.
-    CommittingKernelNomt([u8; 32]),
+    CommittingKernelNomt,
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/commit_flag.rs:14]: Why we are not writing root hashes into flags anymore?

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 3 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: Fixed

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 4 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:102]: The reason is in the PR description. It is redundant with the state root hash form 'live_db`

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 5 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: Fixed

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 6 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:181]: It was extracted to  `state_roots.warning_on_rollback(&commit_status)`  (for example in line 170)

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 7 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: fixed

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 8 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: removed

File: crates/full-node/sov-db/src/commit_flag.rs (hunk 9 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/commit_flag.rs:14]: The `live_db` is committed last. This allows us to perform the same checks we previously had (with the root hash saved in a file). If any earlier database contains the same root hash as live_db (and the status is different than Success), it indicates that it was not committed in the previous run.

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 10]
```diff
@@ -551,3 +479,102 @@ impl PrunerJob {
...
+    pre_genesis_root[32..].copy_from_slice(&nomt::trie::TERMINATOR);
+    pre_genesis_root
+}
+
+struct AllDBsStateRoots {
+    // The `live_db` is committed last. We can use `root_hash_from_live_db` to verify
+    // whether all other databases were committed in the previous run.
+    root_hash_from_live_db: [u8; 64],
+    root_hash_from_ledger_db: [u8; 64],
+    root_hash_nomt: StateRootHashes,
```
Comment (bkolad) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:517]: In the next PRs we will add  root_hash for accessory & archival

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 4 above)
Comment (citizen-stig) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:102]: Ok, so just to clarify my understanding:

* Live DB has "canonical" root hash, because it is committed the last.
* If root hash from any other DB does not match it, it is rolled back.

Correct?

**Review by citizen-stig — APPROVED** [review]
