### PR TITLE
Testing utility for checking rollup crashes

### LINKED ISSUE #2267: Prevent database corruption on ungraceful shutdown
## Background
Currently, ungraceful shutdowns during DB commit can leave the database in an inconsistent state. 

## Design
To prevent issues, we need to make minor changes to the rollup's startup sequence, the commit-flag enum, and the commit flow.

```rust
enum CommitFlag { 
   Successful { height: u64 },
   ComittingKernelNomt { height: u64 },
   ComittingUserNomt { height: u64 },
   ComittingRocksDB{ height: u64 },
}

```

On startup, check `commit flag`
	1. If status is successful, start from the height +1
	2. If `ComittingKernelNomt`, check whether the commit finished by comparing the NOMT root to the root stored in the live state table. If they match, no rollback is required. Otherwise, roll back kernel NOMT. Start from `height`
	3. If `ComittingUserNomt` in progress, check whether the commit finished by comparing the NOMT root to the root stored in the live state table. If the roots matched, the commit didn't succeed and we're safe.  Start from `height`
		1. If the roots do *not* match, this means NOMT is out of sync with the flat state. To recover we can either
			1. Enable rollback for user NOMT (not ideal)
			2. Skip the consistency check (and update, which would be a no-op anyway) on the next commit
			3. Note that witness generation will be impossible until the next commit. SO, when we enable proving, commit the witness *before* updating the NOMT instance. 

On commit: 
1. Commit ledger and accessory state. These can't be used read block execution - so they should be safe even if they're not fully consistent; they'll get overwritten with the same data when we process the block again (TODO: Verify this is true of accessory state; might be used in sequencer for state root calcs etc.) 
2. Update flag -> `ComittingKernelNomt` { height: u64 },
3. Commit kernel NOMT.
	1. NOMT claims to provide crash fault tolerance through a WAL, so this is atomic
4. Update flag to `ComittingUserNomt`
5. Commit user NOMT
6. Update flag to `CommittingRocksDB`
7. Commit all kernel/user DBs as a unit (remove "other" - it only contains a singleton which can be put in the main DBs;
	1. Commit archival first. If this fails, it'll get overwritten with identical values on the next run
	2. Commit all flat values atomically. 
8. Update flag to Successful

### PR DESCRIPTION
**Pull request by bkolad**
# Description

A small utility and example tests for verifying whether the rollup can recover after a hard crash.
The idea is that in the tests, we set the `CrashLocation` via an environment variable, and then we check whether the rollup is healthy after restarting.

- [x] ~I have updated `CHANGELOG.md` with a new entry if my PR makes any breaking changes or fixes a bug. If my PR removes a feature or changes its behavior, I provide help for users on how to migrate to the new behavior.~
- [x] I have carefully reviewed all my `Cargo.toml` changes before opening the PRs. (Are all new dependencies necessary? Is any module dependency leaked into the full-node (hint: it shouldn't)?)

### CODE REVIEW

File: examples/demo-rollup/tests/restart/crash.rs [hunk 1]
```diff
@@ -0,0 +1,251 @@
...
+            nb_of_events += 1;
+            assert!(
+                nb_of_events < max_nb_of_txs,
+                "The node didn't crash, but it was expected to."
+            );
+        }
+    }
+
+    // Give the OS time to clean up file handles after the crash.
+    tokio::time::sleep(std::time::Duration::from_millis(1000)).await;
```
Comment (bkolad) [inline examples/demo-rollup/tests/restart/crash.rs:144]: Unfortunately, I didn't find a way to remove this delay.

File: crates/full-node/sov-db/src/test_utils.rs [hunk 2]
```diff
@@ -290,3 +290,41 @@ fn is_version_selected_for_key(
...
+#[derive(Debug, Clone, Display, EnumString, Eq, PartialEq)]
+pub enum CrashLocation {
+    /// Rollup crashes before saving `the CommittingKernelNomt` flag.
+    BeforeSavingKernelNomt,
+    /// Rollup crashes before committing the kernel.
+    BeforeCommittingKernelNomt,
+    /// Rollup crashes before saving the `CommittingUserNomt` flag.
+    BeforeSavingUserlNomt,
+    /// Rollup crashes before committing the user nomt.
+    BeforeCommittingUserNomt,
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/test_utils.rs:309]: I think it is very important to add failures after commit is done, but before flag is written.

File: crates/full-node/sov-db/Cargo.toml [hunk 3]
```diff
@@ -44,6 +44,7 @@ serde_with = { workspace = true }
 derivative = { workspace = true }
 digest = { workspace = true }
 sov-db-types = { workspace = true, features = ["native"] }
+strum = { workspace = true, features = ["derive"], optional = true}
```
Comment (citizen-stig) [inline crates/full-node/sov-db/Cargo.toml]:
```suggestion
strum = { workspace = true, features = ["derive"], optional = true }
```

File: examples/demo-rollup/tests/restart/graceful.rs [hunk 4]
```diff
@@ -0,0 +1,483 @@
+//! Tests for shutdown/restart cases.
```
Comment (citizen-stig) [inline examples/demo-rollup/tests/restart/graceful.rs:1]: Just to clarify, `graceful.rs` is moved from mod.rs, right?

Comment (bkolad) [reply examples/demo-rollup/tests/restart/graceful.rs:1]: yep

File: crates/full-node/sov-db/Cargo.toml (hunk 3 above)
Comment (bkolad) [reply crates/full-node/sov-db/Cargo.toml]: fixed

**Review by citizen-stig — APPROVED** [review]
