### PR TITLE
sov-db: Track DB commit status

### LINKED ISSUE #2267: Prevent database corruption on ungraceful shutdown
## Background
Currently, ungraceful shutdowns during DB commit can leave the database in an inconsistent state. 

## Design
To prevent issues, we need to make minor changes to the rollup's startup sequence, the commit-flag enum, and the commit flow.

```rust
enum CommitFlag { 
   Successful { height: u64 },
   ComittingKernelNomt { height: u64 },
   ComittingUserNomt { height: u64 },
   ComittingRocksDB{ height: u64 },
}

```

On startup, check `commit flag`
	1. If status is successful, start from the height +1
	2. If `ComittingKernelNomt`, check whether the commit finished by comparing the NOMT root to the root stored in the live state table. If they match, no rollback is required. Otherwise, roll back kernel NOMT. Start from `height`
	3. If `ComittingUserNomt` in progress, check whether the commit finished by comparing the NOMT root to the root stored in the live state table. If the roots matched, the commit didn't succeed and we're safe.  Start from `height`
		1. If the roots do *not* match, this means NOMT is out of sync with the flat state. To recover we can either
			1. Enable rollback for user NOMT (not ideal)
			2. Skip the consistency check (and update, which would be a no-op anyway) on the next commit
			3. Note that witness generation will be impossible until the next commit. SO, when we enable proving, commit the witness *before* updating the NOMT instance. 

On commit: 
1. Commit ledger and accessory state. These can't be used read block execution - so they should be safe even if they're not fully consistent; they'll get overwritten with the same data when we process the block again (TODO: Verify this is true of accessory state; might be used in sequencer for state root calcs etc.) 
2. Update flag -> `ComittingKernelNomt` { height: u64 },
3. Commit kernel NOMT.
	1. NOMT claims to provide crash fault tolerance through a WAL, so this is atomic
4. Update flag to `ComittingUserNomt`
5. Commit user NOMT
6. Update flag to `CommittingRocksDB`
7. Commit all kernel/user DBs as a unit (remove "other" - it only contains a singleton which can be put in the main DBs;
	1. Commit archival first. If this fails, it'll get overwritten with identical values on the next run
	2. Commit all flat values atomically. 
8. Update flag to Successful

### PR DESCRIPTION
**Pull request by bkolad**
# Description

This PR adds tracking for DB commit status.

Previously, the `CommitFlag` mechanism saved the `CommitStatus` to a file, but it had two major limitations:
1. It did not cover all possible database shutdown scenarios.
2. The flag was written after committing a specific DB. It is now written before the commit, which simplifies error handling.

The `CommitStatus` is now written to a file in the `DbGroup::commit` method, and recovery is performed in `NomtStateDb::`validate_commit_flag_and_rollback_if_necssesary.

Unit tests will be included in a follow-up PR.

- [x] ~I have updated `CHANGELOG.md` with a new entry if my PR makes any breaking changes or fixes a bug. If my PR removes a feature or changes its behavior, I provide help for users on how to migrate to the new behavior.~
- [ ] I have carefully reviewed all my `Cargo.toml` changes before opening the PRs. (Are all new dependencies necessary? Is any module dependency leaked into the full-node (hint: it shouldn't)?)

## Linked Issues
- Related to #2267

### CODE REVIEW

File: crates/full-node/sov-db/src/state_db_nomt.rs [hunk 1]
```diff
@@ -544,8 +538,6 @@ mod tests {
     // Then we create 2 more overlays on top of those 2, let's call them "test overlays".
     // Then the "base" kernel overlay is committed, but the "user" base overlay is kept in memory.
     // This creates a precondition for `StateOverlay::commit` to fail on the user overlay phase.
-    // After this error is confirmed, we commit the "base user" overlay and re-open the NOMT database.
```
Comment (bkolad) [inline crates/full-node/sov-db/src/state_db_nomt.rs:547]: This test is not relevant anymore, and will be replaced in the next PR.

File: crates/full-node/sov-db/src/lib.rs [hunk 2]
```diff
@@ -35,7 +35,7 @@ pub mod accessory_db;
 pub mod namespaces;
 
 /// Implements commit flag logic for state_db_nomt.
-pub(crate) mod commit_flag;
+pub mod commit_flag;
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/lib.rs:39]: Why should it become public? if it is only for `sov-test-utils`, then let's make it public only if `test-utils` is enabled. 

I don't want to expose too much of internals outside of the crate

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 3]
```diff
@@ -350,20 +376,6 @@ where
             }
         }
     }
-
-    pub(crate) fn verify_and_fix_commited_root_hashes(&self) -> anyhow::Result<()> {
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:354]: Why we don't do this check anymore?

File: crates/full-node/sov-db/src/storage_manager/nomt_based/mod.rs [hunk 4]
```diff
@@ -138,8 +138,6 @@ where
             "Pruner versions to keep should be at least 1, got {pruner_versions_to_keep}",
         );
         let db_group = DbGroup::new(config)?;
-
-        db_group.verify_and_fix_commited_root_hashes()?;
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/mod.rs:142]: Why we don't do this check anymore?

File: crates/full-node/sov-db/src/commit_flag.rs [hunk 5]
```diff
@@ -120,80 +127,12 @@ impl CommitFlag {
         Ok(())
     }
 
-    pub fn log_reset_instruction(&self) {
-        tracing::error!(
-            "To reset commit flag, please remove commit flag file: `rm {}`",
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/commit_flag.rs:125]: This was useful if user knows that it just wants to remove flag, they can just copy command and execute it. Why we removed it?

File: crates/full-node/sov-db/src/flat_db.rs [hunk 6]
```diff
@@ -203,10 +208,14 @@ impl FlatStateDb {
             &self.live_db,
         )?;
 
-        // Write batches.
+        // Write archival db batches.
+        commit_flag.save_commit_status(&CommitStatus::CommittingArchivalUserAndKernel)?;
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/flat_db.rs:212]: Nit: what do you think about debug_assert that previous state is matching expected state of NOMT being commited (without actually checking root hash)

File: crates/full-node/sov-db/src/state_db_nomt.rs [hunk 7]
```diff
@@ -19,142 +20,117 @@ const BOTH: &str = "user_and_kernel_state";
...
-            return Err(flag_write_err).with_context(|| {
-                self.commit_flag.log_reset_instruction();
-                "Failed to write IN-PROGRESS status after kernel commit; kernel was rolled back, but flag does not match. Manual intervention required."
-            });
-        }
-
-        debug_assert_eq!(self.commit_flag.read_status()?, in_progress_commit_status);
+        commit_flag.save_commit_status(&CommitStatus::CommittingKernelNomt(
+            self.kernel.root().into_inner(),
+        ))?;
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/state_db_nomt.rs:119]: What happens if NOMT has commited successfully, but writing flag has failed?

File: crates/full-node/sov-db/src/state_db_nomt.rs [hunk 8]
```diff
@@ -19,142 +20,117 @@ const BOTH: &str = "user_and_kernel_state";
...
-        let user = {
-            let opts = config.get_user_options();
-            Nomt::<BinaryHasher<H>>::open(opts)?
-        };
+            CommitStatus::CommittingArchivalUserAndKernel
+            | CommitStatus::CommittingLiveUserAndKernel => {
+                tracing::warn!(
+                "Detected in-progress commit {commit_status:?}. Rolling back kernel & user DBs."
+            );
+                // User & Kernel commit was sucefull but we don't see `Success`. We rollback both User & Kernek.
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/state_db_nomt.rs]:
```suggestion
                // User & Kernel commit was successful but we don't see `Success`. We rollback both User & Kernel.
```

File: crates/full-node/sov-db/src/state_db_nomt.rs [hunk 9]
```diff
@@ -19,142 +20,117 @@ const BOTH: &str = "user_and_kernel_state";
...
-        }
 
-        let user = {
-            let opts = config.get_user_options();
-            Nomt::<BinaryHasher<H>>::open(opts)?
-        };
+            CommitStatus::CommittingArchivalUserAndKernel
+            | CommitStatus::CommittingLiveUserAndKernel => {
+                tracing::warn!(
+                "Detected in-progress commit {commit_status:?}. Rolling back kernel & user DBs."
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/state_db_nomt.rs]: nit: Can we make `commit_status` as an attribute?

**Review by citizen-stig — CHANGES_REQUESTED** [review]
Overall is good, left couple of comments

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 10]
```diff
@@ -47,13 +49,27 @@ where
...
+        // Validate root hashes.
+        Self::are_root_hashes_match(&merklized_state, &flat_state)?;
+
         let accessory_rocksdb =
             AccessoryDb::get_rockbound_options().default_setup_db_in_path(&path)?;
         let ledger_rocksdb = LedgerDb::get_rockbound_options().default_setup_db_in_path(&path)?;
-        let flat_state = FlatStateDb::new(path, state_cache_size, separate_archival_state)?;
+
+        // After validation override the commit flag to Success.
+        commit_flag.write_status(&CommitStatus::Success)?;
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: What happens if we commited live-db successfully, but failed to write commit status `Success` ?

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 3 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:354]: We do it in`DbGroup::new`

File: crates/full-node/sov-db/src/storage_manager/nomt_based/mod.rs (hunk 4 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/mod.rs:142]: We do it in `DbGroup::new`

File: crates/full-node/sov-db/src/commit_flag.rs (hunk 5 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/commit_flag.rs:125]: Why would we ever want to reset the flag manually? The flow has changed and now we save the file before committing the nomt.

File: crates/full-node/sov-db/src/state_db_nomt.rs (hunk 7 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/state_db_nomt.rs:119]: We set the flag before committing to Nomt, so if saving the flag fails, we won’t attempt the Nomt commit

File: crates/full-node/sov-db/src/lib.rs (hunk 2 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/lib.rs:39]: fixed

File: crates/full-node/sov-db/src/state_db_nomt.rs (hunk 8 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/state_db_nomt.rs]: fixed

File: crates/full-node/sov-db/src/state_db_nomt.rs (hunk 9 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/state_db_nomt.rs]: fixed

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 10 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: We discussed this with Preston when you ware on holiday:

1. We will rollback both the `user` and `kernel` so they remain in a consistent state. 
2. The flat-db and ledger will temporarily be ahead of Nomt, 
3. On startup, the rollup will start from the latest height committed to nomt. After processing the first block, we will override the flat-db/ledger

File: crates/full-node/sov-db/src/flat_db.rs (hunk 6 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/flat_db.rs:212]: Inside `save_commit_status` there is a check that the status was saved. 
```
   pub(crate) fn save_commit_status(&self, commit_status: &CommitStatus) -> anyhow::Result<()> {
        self.write_status(commit_status).with_context(|| {
            format!("Failed to write {commit_status:?} status after successful user commit")
        })?;

        debug_assert_eq!(&self.read_status()?, commit_status);
        Ok(())
    }
```

File: crates/full-node/sov-db/src/commit_flag.rs [hunk 11]
```diff
@@ -7,14 +7,21 @@ use borsh::{BorshDeserialize, BorshSerialize};
...
+    /// Stores the previous `kernel` root hash before the commit began.
+    CommittingKernelNomt([u8; 32]),
+    /// A commit of **user state** is in progress.
+    /// Stores the previous `user` root hash before the commit began.
+    CommittingUserNomt([u8; 32]),
+    /// A commit of **archival user and kernel state** in the flat-db is in progress.
+    CommittingArchivalUserAndKernel,
+    /// A commit of **live live user and kernel state** in the flat-db is in progress.
+    CommittingLiveUserAndKernel,
+    /// The commit suceeded.
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/commit_flag.rs]:
```suggestion
    /// The commit succeeded.
```

File: crates/full-node/sov-db/src/commit_flag.rs [hunk 12]
```diff
@@ -7,14 +7,21 @@ use borsh::{BorshDeserialize, BorshSerialize};
...
-    Completed,
+    /// A commit of **kernel state** is in progress.
+    /// Stores the previous `kernel` root hash before the commit began.
+    CommittingKernelNomt([u8; 32]),
+    /// A commit of **user state** is in progress.
+    /// Stores the previous `user` root hash before the commit began.
+    CommittingUserNomt([u8; 32]),
+    /// A commit of **archival user and kernel state** in the flat-db is in progress.
+    CommittingArchivalUserAndKernel,
+    /// A commit of **live live user and kernel state** in the flat-db is in progress.
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/commit_flag.rs]:
```suggestion
    /// A commit of **live user and kernel state** in the flat-db is in progress.
```

File: crates/full-node/sov-db/src/state_db_nomt.rs [hunk 13]
```diff
@@ -19,142 +20,121 @@ const BOTH: &str = "user_and_kernel_state";
...
-            let opts = config.get_user_options();
-            Nomt::<BinaryHasher<H>>::open(opts)?
-        };
+            CommitStatus::CommittingArchivalUserAndKernel
+            | CommitStatus::CommittingLiveUserAndKernel => {
+                tracing::warn!(
+                    ?commit_status,
+                    "Detected in-progress commit. Rolling back kernel & user DBs."
+                );
+                // User & Kernel commit was sucefull but we don't see `Success`. We rollback both User & Kernel.
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/state_db_nomt.rs]:
```suggestion
                // User & Kernel commit was successful but we don't see `Success`. We rollback both User & Kernel.
```

File: crates/full-node/sov-db/src/state_db_nomt.rs [hunk 14]
```diff
@@ -19,142 +20,121 @@ const BOTH: &str = "user_and_kernel_state";
...
+                self.kernel.rollback(1)?;
+                self.user.rollback(1)?;
+            }
+            CommitStatus::Success => {}
+        }
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/state_db_nomt.rs]: Do we need to update flag to success at the end, so it is consistent on the next restart?

Comment (citizen-stig) [reply crates/full-node/sov-db/src/state_db_nomt.rs]: Meaning if it accidentally shut down immediately before starting new block

File: crates/full-node/sov-db/src/state_db_nomt.rs [hunk 15]
```diff
@@ -19,142 +20,121 @@ const BOTH: &str = "user_and_kernel_state";
...
-                        hex::encode(current_kernel_root_hash),
+        let user = {
+            let opts = config.get_user_options();
+            Nomt::<BinaryHasher<H>>::open(opts)?
+        };
+
+        Ok(Self { user, kernel })
+    }
+
+    pub(crate) fn validate_commit_flag_and_rollback_if_necssesary(
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/state_db_nomt.rs]:
```suggestion
    pub(crate) fn validate_commit_flag_and_rollback_if_necessesary(
```

Comment (bkolad) [reply crates/full-node/sov-db/src/state_db_nomt.rs]: fixed

File: crates/full-node/sov-db/src/state_db_nomt.rs (hunk 14 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/state_db_nomt.rs]: Added the save in `DbGroup::new`

File: crates/full-node/sov-db/src/state_db_nomt.rs (hunk 15 above)
Comment (bkolad) [reply crates/full-node/sov-db/src/state_db_nomt.rs]: fixed

File: crates/full-node/sov-db/src/state_db_nomt.rs (hunk 7 above)
Comment (citizen-stig) [reply crates/full-node/sov-db/src/state_db_nomt.rs:119]: Discussed offline

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs (hunk 10 above)
Comment (citizen-stig) [reply crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs]: Discussed offline. Fixes are going to be done in future PRs

File: crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs [hunk 16]
```diff
@@ -62,6 +77,8 @@ where
     }
 
     pub(crate) fn commit(&mut self, group: CommitGroup) -> anyhow::Result<()> {
+        // The last commit had to be successful.
+        debug_assert_eq!(&self.commit_flag.read_status()?, &CommitStatus::Success);
```
Comment (citizen-stig) [inline crates/full-node/sov-db/src/storage_manager/nomt_based/groups.rs:81]: Non blocking: What if it is going to be normal assert? It will add couple ms to the commit time, which is not great, but give extra safety

**Review by citizen-stig — APPROVED** [review]
